language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_moudles

node_js: stable

install:
  - npm install -D
  - cd ./test/template
  - npm install -D
  - cd ../../

scripts:
  - npm test:unit
