language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_moudles

node_js: stable

install:
  - npm install pnpm -g
  - pnpm install
  - cd ./test/template
  - pnpm install -D
  - cd ../../

scripts:
  - pnpm cover
